# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-18 11:46
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='avitoflats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateBegin', models.DateField(verbose_name='Дата начала размещения объявления:')),
                ('DateEnd', models.DateField(verbose_name='Дата  до которых объявление актуально:')),
                ('Street', models.CharField(help_text='Например Гагарина', max_length=55, verbose_name='Улица:')),
                ('House_Numb', models.CharField(help_text='например 36', max_length=55, verbose_name='Номер дома:')),
                ('Description', models.TextField(verbose_name='Oписание объявления:')),
                ('Price', models.IntegerField(default=800000, validators=[django.core.validators.MinValueValidator(300000)], verbose_name='Цена в рублях:')),
                ('AdStatus', models.CharField(choices=[('Free', 'Free'), ('Premium', 'Premium'), ('VIP', 'VIP'), ('PushUp', 'PushUp'), ('Highlight', 'Highlight'), ('TurboSale', 'TurboSale'), ('QuickSale', 'QuickSale')], max_length=55, verbose_name='Платная услуга:')),
                ('Rooms', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество комнат в квартире:')),
                ('Square', models.IntegerField(validators=[django.core.validators.MinValueValidator(10)], verbose_name='Общая площадь объекта:')),
                ('Floor', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Этаж:')),
                ('Floors', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество этажей в доме:')),
                ('HouseType', models.CharField(max_length=35, verbose_name='Тип дома:')),
                ('MarketType', models.CharField(choices=[('Вторичка', 'Вторичка'), ('Новостройка', 'Новостройка')], max_length=35, verbose_name='Принадлежность квартиры к рынку:')),
            ],
            options={
                'verbose_name': 'Выгрузка на Авито',
                'verbose_name_plural': 'Выгрузка на Авито',
            },
        ),
    ]
