# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-19 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avito', '0002_avitoflats_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avitoflats',
            name='AdStatus',
            field=models.CharField(choices=[('Free', 'Обычное'), ('Premium', 'Премиум-объявление;'), ('VIP', 'VIP-объявление'), ('PushUp', 'Поднятие объявления в поиске'), ('Highlight', 'Выделение объявления'), ('TurboSale', 'Турбо-продажа'), ('QuickSale', 'Быстрая продажа')], max_length=55, verbose_name='Платная услуга:'),
        ),
        migrations.AlterField(
            model_name='avitoflats',
            name='HouseType',
            field=models.CharField(choices=[('Кирпичный', 'Кирпичный'), ('Панельный', 'Панельный'), ('Блочный', 'Блочный'), ('Монолитный', 'Монолитный'), ('Деревянный', 'Деревянный')], max_length=35, verbose_name='Тип дома:'),
        ),
    ]
