# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-19 11:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avito', '0003_auto_20181219_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='avito_gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, verbose_name='Дата создания')),
                ('npict', models.ImageField(upload_to='image/%Y/%m/%d/avito', verbose_name='Фото объекта')),
                ('id_gal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idd_gal', to='avito.avitoflats', verbose_name='Название')),
            ],
            options={
                'verbose_name_plural': 'Выгрузки галерея (Avito)',
                'verbose_name': 'Выгрузки галерея (Avito)',
            },
        ),
    ]
