# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-22 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avito', '0006_auto_20181220_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avitoflats',
            name='AdStatus',
            field=models.CharField(choices=[('Неопубликованно', 'Неопубликованно'), ('Обычное', 'Обычное'), ('Премиум-объявление', 'Премиум-объявление'), ('VIP-объявление', 'VIP-объявление'), ('Поднятие объявления в поиске', 'Поднятие объявления в поиске'), ('Выделение объявления', 'Выделение объявления'), ('TurboSale', 'Турбо-продажа'), ('QuickSale', 'Быстрая продажа')], max_length=55, verbose_name='Платная услуга:'),
        ),
    ]
