# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-22 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avito', '0009_auto_20181222_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avitoflats',
            name='DateBegin',
            field=models.DateField(null=True, verbose_name='Дата начала размещения объявления:'),
        ),
        migrations.AlterField(
            model_name='avitoflats',
            name='DateEnd',
            field=models.DateField(null=True, verbose_name='Дата окончания публикации объявления:'),
        ),
    ]
